services:
  echo-speaks-server:
    image: echo-speaks-server:2.7.2
    build: 
      context: ../
    container_name: echo-speaks-server
    restart: always

    ports:
      - "8091:8091"
    env_file:
      - './env.echo-speaks-server'
    volumes:
      # Data persistency
      - ./data:/mnt/es-data

